config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :idioms
  resources :countries
  root 'index#index'
  
  
  get 'index/index'
  get 'login/login'
  get 'selection/selection'
  
  post 'selection/searchresults' => 'selection#searchresults'
  
  post 'contact/create' => 'contacts#create'
  
  get 'activities/themesort'
  get 'activities/guessing'
  get 'activities/oneword'
  
  get 'main/main'
  get 'main/mainguessing'
  get 'main/mainoneword'
  
  get 'user_idiom/users_idioms'
  post 'user_idiom/create' => 'user_idiom#create'
  
  post '/login/auth' => 'login#auth'
  
  

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def  main
        @user=User.find(params[:user_id])
        if (params.has_key?(:activity))
            @activity = "activities/"+params[:activity].to_s()
            @arr = params[:array]
        else
            @activity = "activities/activitygeneric"
        end
    end
    
    def  mainguessing
    end     
       
    def  mainoneword
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.permit(:activity)
    end 
end

app/views/main/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/css/main.css" rel="stylesheet">
    <script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
</head>
<div class="modal-body">
    <div class="col-md-3" id="contact-profile">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <h4>Current connection</h4>    
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <img id="user-icon" src="../images/userpic_elderly.png" class="img-responsive"/>
            </div>
            <div class="col-xs-8">
                <h3><strong><%= @user.name%></strong></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <h4><strong>Bio:</strong></h4>
                <p><%= @user.bio%></p>
                <h4><strong>Gender:</strong> <%= @user.gender%></h4>
                <h4><strong>Knows:</strong></h4>
                <h4><strong>Learning:</strong></h4>
                <h4><strong>Skype:</strong></h4>
                <h4>
                    <div id="SkypeButton_Call">
                         <script type="text/javascript">
                             Skype.ui({
                             "name": "call",
                             "element": "SkypeButton_Call",
                             "participants": ["<%= @user.skypeusername%>"],
                             "imageSize": 32
                             });
                         </script>
                    </div>
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <% if !Contact.find_by(:owner_id => current_user.id, :user_id => @user.id) %>
                    <%= button_to 'Add contact', contact_create_url(:owner_id => current_user.id, :user_id => @user.id), method: :post, :class => 'btn btn-default'%>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="conversation-content">
        <%= render partial: @activity %>
    </div>
    <div class="col-md-3" id="conversation-options">
        <h3>Start another activity</h3>
        <%= link_to render(partial: 'activities/activitysummary', :locals => {:activitytitle => "Themesort", :activityname => "themesort"}), main_main_url(:activity => "themesort", :user_id => @user.id), method: :get, :class => 'home_links' %>
        <%= link_to render(partial: 'activities/activitysummary', :locals => {:activitytitle => "Guessing", :activityname => "guessing"}), main_main_url(:activity => "guessing", :user_id => @user.id), method: :get, :class => 'home_links' %>
        <%= link_to render(partial: 'activities/activitysummary', :locals => {:activitytitle => "One Word", :activityname => "oneword"}), main_main_url(:activity => "oneword", :user_id => @user.id), method: :get, :class => 'home_links' %>    
    </div>
</div>

app/views/main/mainguessing.html.erb
<!DOCTYPE html>
<html lang="en">
    <% arr = [
"Trip",
"Dominoes",
"Circus",
"Spring",
"Toast",
"Treasure",
"Pirate",
"Frog",
"Eletricity",
"Nature",
"Outside",
"Ski",
"Palace",
"Deep",
"Music",
"Song"
    ] %>

<head>
    <!--<link href="/css/login/loginstyles.css" rel="stylesheet">-->
    <link href="/css/main.css" rel="stylesheet">
</head>
<body id="body-content">
    <div class="modal-body row">
        <div class="col-md-3" id="user-profile">
            <div class="row">
                <div class="col-xs-6">
                    <img id="user-icon" src="../images/william_oMaley.jpg" class="img-responsive"/>
                </div>
                <div class="col-s-6">
                    Current connection:
                    <h3 class="text-justify">William O'Maley</h3>
                    <!--<h3 class="text-justify"><%= current_user.name %></h3>-->
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    Connection Profile
                </div>
                <div class="col-xs-12">
                    Marital Status: Widower
                </div>
                <div class="col-xs-12">
                    Language: English
                </div>
                <div class="col-xs-12">
                    Hobbies: Snooker, Cards, bowling
                </div>
                <div class="col-xs-12">
                    Country: United States
                </div>
                <div class="col-xs-12">
                    Link Skype:
                </div>
            </div>
            
            <!--
            <div class="row">
                
                <h2>Contacts</h2>
                
                <ul>
                    <button class="btn btn-default btn-action">
                            <img src="../images/william_oMaley.jpg" width="25" /> William O'Maley
                    </button>
                    
                    
                    <button class="btn btn-default btn-action">
                            <img src="../images/katie_johnson.jpg" width="25" /> Katie Johnson   
                    </button>
                    

                    <button class="btn btn-default btn-action">
                            <img src="../images/mary_edwards.jpg" width="25" /> Mary Edwards
                    </button>
                    
                    </ul>
                
            </div>
            -->
            
            <!-- ../images/userpic_elderly.png -->
            <!--<div class="row small">Icons made by <a href="http://www.freepik.com" title=" Freepik ">Freepik</a> from <a href="https://www.flaticon.com/" title=" Flaticon ">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title=" Creative Commons BY 3.0 " target="_blank">CC 3.0 BY</a>
            </div>-->
        </div>
        <div class="col-md-6"id="conversation-content">
            <div class="row" id="conversation-content-activity">
                <h1>Current Activity: Guessing</h1>
                <h3>Try to explain the stuff sorted to your connection.</h3>
                <header class="masthead">
                  <div class="header-content">
                    <div class="header-content-inner" style="background-color: white;">
                      <h1>Stuff Sorted: <%= arr.at(rand(0..15)) %></h1>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#">Resort</a>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="javascript:history.back()">Back</a>
                    </div>
                  
                  </div>
                </header>
            </div>
        </div>
        
        <div class="col-md-3" id="conversation-options">
            <h3>Start another activity</h3>
            <div class="list-group" id="otheractivities">
                
                    <ul>
                    <!--<button class="btn btn-default btn-action">
                            <img src="../images/ativtemas.png" width="50" /> Theme Sort
                    </button>
                    
                    
                    <button class="btn btn-default btn-action">
                            <img src="../images/ativguessing.png" width="50" /> Guessing   
                    </button>
                    

                    <button class="btn btn-default btn-action">
                            <img src="../images/ativoneword.png" width="50" /> One Word
                    </button>
                    -->
                    
                    <a class="list-group-item" href="/main/main"> 
                    <img id="user-icon" src="../images/ativtemas.png" class="img-responsive"/>
                    <h4>Theme Sort </h4>
                    </a>
                    <a class="list-group-item" href="/main/mainguessing"> 
                    <img id="user-icon" src="../images/ativguessing_s.png" class="img-responsive"/>
                    <h4>Guessing </h4>
                    </a>
                    <a class="list-group-item" href="/main/mainoneword"> 
                    <img id="user-icon" src="../images/ativoneword_s.png" class="img-responsive"/>
                    <h4>One Word </h4>
                    </a>
                    
                    </ul>
                    
                </div>
            </div>    
        </div>
        <!--<div class="row" id="conversation-content-activity">
            <div class="col-md-12">
                Current Activity
            </div>
        </div>
        -->
    </div> 
</body>

app/views/main/mainoneword.html.erb
<!DOCTYPE html>
<html lang="en">
    <% arr = [
"Mother",
"Father",
"Teacher",
"Health",
"Friends",
"Heart",
"technology",
"Youth",
"Retirement",
"Nursing Home",
"Family",
"Conversation",
"Study",
"Life",
"Gym",
"Stories",
"History"
    ] %>

<head>
    <!--<link href="/css/login/loginstyles.css" rel="stylesheet">-->
    <link href="/css/main.css" rel="stylesheet">
</head>
<body id="body-content">
    <div class="modal-body row">
        <div class="col-md-3" id="user-profile">
            <div class="row">
                <div class="col-xs-6">
                    <img id="user-icon" src="../images/william_oMaley.jpg" class="img-responsive"/>
                </div>
                <div class="col-s-6">
                    Current connection:
                    <h3 class="text-justify">William O'Maley</h3>
                    <!--<h3 class="text-justify"><%= current_user.name %></h3>-->
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    Connection Profile
                </div>
                <div class="col-xs-12">
                    Marital Status: Widower
                </div>
                <div class="col-xs-12">
                    Language: English
                </div>
                <div class="col-xs-12">
                    Hobbies: Snooker, Cards, bowling
                </div>
                <div class="col-xs-12">
                    Country: United States
                </div>
                <div class="col-xs-12">
                    Link Skype:
                </div>
            </div>
            
            <!--
            <div class="row">
                
                <h2>Contacts</h2>
                
                <ul>
                    <button class="btn btn-default btn-action">
                            <img src="../images/william_oMaley.jpg" width="25" /> William O'Maley
                    </button>
                    
                    
                    <button class="btn btn-default btn-action">
                            <img src="../images/katie_johnson.jpg" width="25" /> Katie Johnson   
                    </button>
                    

                    <button class="btn btn-default btn-action">
                            <img src="../images/mary_edwards.jpg" width="25" /> Mary Edwards
                    </button>
                    
                    </ul>
                
            </div>
            -->
            
            <!-- ../images/userpic_elderly.png -->
            <!--<div class="row small">Icons made by <a href="http://www.freepik.com" title=" Freepik ">Freepik</a> from <a href="https://www.flaticon.com/" title=" Flaticon ">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title=" Creative Commons BY 3.0 " target="_blank">CC 3.0 BY</a>
            </div>-->
        </div>
        <div class="col-md-6"id="conversation-content">
            <div class="row" id="conversation-content-activity">
                <h1>Current Activity: One Word</h1>
                <h3>You need to tell your connection what word was sorted and your connection need to explain what 
                    this means to him/her with one word.</h3>
                <header class="masthead">
                  <div class="header-content">
                    <div class="header-content-inner" style="background-color: white;">
                      <h1>Stuff Sorted: <%= arr.at(rand(0..15)) %></h1>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#">Resort</a>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="javascript:history.back()">Back</a>
                    </div>
                  
                  </div>
                </header>
            </div>
        </div>
        
        <div class="col-md-3" id="conversation-options">
            <h3>Start another activity</h3>
            <div class="list-group" id="otheractivities">
                
                    <ul>
                    <!--<button class="btn btn-default btn-action">
                            <img src="../images/ativtemas.png" width="50" /> Theme Sort
                    </button>
                    
                    
                    <button class="btn btn-default btn-action">
                            <img src="../images/ativguessing.png" width="50" /> Guessing   
                    </button>
                    

                    <button class="btn btn-default btn-action">
                            <img src="../images/ativoneword.png" width="50" /> One Word
                    </button>
                    -->
                    
                    <a class="list-group-item" href="/main/main"> 
                    <img id="user-icon" src="../images/ativtemas.png" class="img-responsive"/>
                    <h4>Theme Sort </h4>
                    </a>
                    <a class="list-group-item" href="/main/mainguessing"> 
                    <img id="user-icon" src="../images/ativguessing_s.png" class="img-responsive"/>
                    <h4>Guessing </h4>
                    </a>
                    <a class="list-group-item" href="/main/mainoneword"> 
                    <img id="user-icon" src="../images/ativoneword_s.png" class="img-responsive"/>
                    <h4>One Word </h4>
                    </a>
                    
                    </ul>
                    
                </div>
            </div>    
        </div>
        <!--<div class="row" id="conversation-content-activity">
            <div class="col-md-12">
                Current Activity
            </div>
        </div>
        -->
    </div> 
</body>