config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :idioms
  resources :countries
  root 'index#index'
  
  
  get 'index/index'
  get 'login/login'
  get 'selection/selection'
  
  post 'selection/searchresults' => 'selection#searchresults'
  
  post 'contact/create' => 'contacts#create'
  
  get 'activities/themesort'
  get 'activities/guessing'
  get 'activities/oneword'
  
  get 'main/main'
  get 'main/mainguessing'
  get 'main/mainoneword'
  
  get 'user_idiom/users_idioms'
  post 'user_idiom/create' => 'user_idiom#create'
  
  post '/login/auth' => 'login#auth'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :country
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :country_id, :address, :gender, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elang</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/creative.css" rel="stylesheet">

  </head>
  <body>
    <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
     <div class="container form-control">
        <div class="field row">
          <div class="col-md-2">
            <%= f.label :name %>  
          </div>
          <div class="col-md-10">
            <%= f.text_field :name %>  
          </div>
        </div>
        <div class="field row">
          <div class="col-md-2">
            <%= f.label :email %>
          </div>
          <div class="col-md-10">
            <%= f.email_field :email %>  
          </div>
        </div>
        <div class="field row">
          <div class="col-md-2">
            <%= f.label :password %>
          </div>
          <div class="col-md-10">
            <%= f.password_field :password %>
          </div>
        </div>
        <div class="field row">
          <div class="col-md-2">
            <%= f.label :country_id %>
          </div>
          <div class="col-md-10">
            <%= select_tag 'country_id', options_for_select(Country.all.map{|country| ["#{country.name}", country.id] }) %>
          </div>
        </div>
        <div class="field row">
          <div class="col-md-2">
            <%= f.label :address %><br>
          </div>
          <div class="col-md-10">
            <%= f.text_field :address %>
          </div>
        </div>
        <div class="actions">
          <div class="row">
            <div class="col-md-4 col-md-offset-1">
              <%= button_tag(type: 'submit', class: "btn btn-submit btn-lg") do %>
              Create my account
              <% end %>
            </div>
            <div class="col-md-4 col-md-offset-6">
              <a class="btn btn-default btn-lg" href='javascript:history.back()'>Go Back
            </div>
          </div>
          <!-- <%=f.submit%> -->
        </div>
        
      <% end %>
    </div>
</body>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Country</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.country %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elang</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/sign-up/signupstyles.css" rel="stylesheet">

  </head>
<body id="body-nav">
  <%= render 'header-footer/header' %>  
</body>
<body id="body-content">
  <div class="container signup-box">
     <div class="row">
       <div class="col-md-12">
         <h2>Sign up</h2>
       </div>
     </div>
     <div class="row">
        <div class="col-md-12">
          <%= render 'form' %>
        </div>
     </div>
  </div>
</body>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1>User Information</h1>
  </div>
  <div class="row" id="notice">
    <%= notice %>
  </div>
  <div class="row h4">
    <strong>Name:</strong>
    <%= @user.name %>
  </div>
  
  <div class="row h4">
    <strong>Email:</strong>
    <%= @user.email %>
  </div>
  
  <div class="row h4">
    <strong>Country:</strong>
    <%= Country.find(@user.country_id).name %>
  </div>
  
  <div class="row h4">
    <strong>Gender:</strong>
    <%= @user.gender %>
  </div>
  
  <div class="row h4">
    <strong>Bio:</strong>
    <%= @user.bio %>
  </div>
  
    <div class="row h4">
    <strong>Skype Username:</strong>
    <%= @user.skypeusername %>
  </div>
  
  <%= link_to 'Edit', edit_user_registration_path(@user), :class => "btn btn-default btn-lg" %>
  <%= link_to 'Home', index_index_url, :class => "btn btn-default btn-lg" %>
  <%= button_to 'My languages', user_idiom_users_idioms_url, :method => :get, :class =>"btn btn-default btn-lg" %>
</div>