config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :idioms
  resources :countries
  root 'index#index'
  
  
  get 'index/index'
  get 'login/login'
  get 'selection/selection'
  
  post 'selection/searchresults' => 'selection#searchresults'
  
  post 'contact/create' => 'contacts#create'
  
  get 'activities/themesort'
  get 'activities/guessing'
  get 'activities/oneword'
  
  get 'main/main'
  get 'main/mainguessing'
  get 'main/mainoneword'
  
  get 'user_idiom/users_idioms'
  post 'user_idiom/create' => 'user_idiom#create'
  
  post '/login/auth' => 'login#auth'
  
  

end

app/models/idiom.rb
class Idiom < ActiveRecord::Base
  belongs_to :Country
end

app/controllers/idioms_controller.rb
class IdiomsController < ApplicationController
  before_action :set_idiom, only: [:show, :edit, :update, :destroy]

  # GET /idioms
  # GET /idioms.json
  def index
    @idioms = Idiom.all
  end

  # GET /idioms/1
  # GET /idioms/1.json
  def show
  end

  # GET /idioms/new
  def new
    @idiom = Idiom.new
  end

  # GET /idioms/1/edit
  def edit
  end

  # POST /idioms
  # POST /idioms.json
  def create
    @idiom = Idiom.new(idiom_params)

    respond_to do |format|
      if @idiom.save
        format.html { redirect_to @idiom, notice: 'Idiom was successfully created.' }
        format.json { render :show, status: :created, location: @idiom }
      else
        format.html { render :new }
        format.json { render json: @idiom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idioms/1
  # PATCH/PUT /idioms/1.json
  def update
    respond_to do |format|
      if @idiom.update(idiom_params)
        format.html { redirect_to @idiom, notice: 'Idiom was successfully updated.' }
        format.json { render :show, status: :ok, location: @idiom }
      else
        format.html { render :edit }
        format.json { render json: @idiom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idioms/1
  # DELETE /idioms/1.json
  def destroy
    @idiom.destroy
    respond_to do |format|
      format.html { redirect_to idioms_url, notice: 'Idiom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idiom
      @idiom = Idiom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idiom_params
      params.require(:idiom).permit(:name, :Country_id)
    end
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/views/idioms/_form.html.erb
<%= form_for(@idiom) do |f| %>
  <% if @idiom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idiom.errors.count, "error") %> prohibited this idiom from being saved:</h2>

      <ul>
      <% @idiom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Country_id %><br>
    <%= f.text_field :Country_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/idioms/edit.html.erb
<h1>Editing Idiom</h1>

<%= render 'form' %>

<%= link_to 'Show', @idiom %> |
<%= link_to 'Back', idioms_path %>

app/views/idioms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Idioms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idioms.each do |idiom| %>
      <tr>
        <td><%= idiom.name %></td>
        <td><%= idiom.Country %></td>
        <td><%= link_to 'Show', idiom %></td>
        <td><%= link_to 'Edit', edit_idiom_path(idiom) %></td>
        <td><%= link_to 'Destroy', idiom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idiom', new_idiom_path %>

app/views/idioms/new.html.erb
<h1>New Idiom</h1>

<%= render 'form' %>

<%= link_to 'Back', idioms_path %>

app/views/idioms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idiom.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @idiom.Country %>
</p>

<%= link_to 'Edit', edit_idiom_path(@idiom) %> |
<%= link_to 'Back', idioms_path %>